### ISSUE TITLE
觀影心得回覆

### ISSUE THREAD

**Issue by azole** [YawenChan/hello-git#1]
謝謝你的觀影筆記跟心得，做得很好耶，資訊領域要學的東西實在太多了，很需要整理資訊的能力，看來這方面你已經做得很好了。你也寫到，希望在資策會剩下的時間，能好好活用影片中的技巧學習，看到你這樣寫，我很開心唷，我私心認為，給自己培養一個適合自己的學習方式，遠比什麼都重要，因為阿，一但找到這個適合自己的方法，還有什麼學不會的呢？剩下的大概就是時間的問題了，用合適自己的方法，然後給自己時間去熟悉跟累積經驗，最後一定可以的。

如果我沒記錯的話，之前的問卷中，你有提到，學習一陣子了，但好像還是不太會寫程式，這個問題可以分幾個角度來看，例如你對基礎的工具是否熟悉？還沒熟悉，那就要趕緊跟上這一塊。如果熟悉，但寫不出來，那就是還沒有把這些工具跟題目連上。無論如何，找到問題點，我們才可以用正確的方式去克服它。你先自己想想看，如果有任何需要，主動來問我或其他老師好嗎？要為自己主動積極地爭取資源，讓自己可以成長，這也是一種需要培養的能力喔。

**Comment by YawenChan** [comment]
Hi 小賴老師,

謝謝老師的鼓勵和意見，問卷的部分是我寫的沒錯。
我覺得我目前的狀況是基礎打得不穩再加上練習不夠所以無法立即連想到要如何寫程式。
目前的計畫會加緊腳步在沒課的時候把JS複習並練得更熟，
如果有問題我會Slack打擾老師的，感謝老師!

Thank you,
詹雅雯



2021年9月24日(金) 21:41 azole ***@***.***>:
